services:
  - type: web
    name: orgtechrepair-web
    env: docker
    plan: free
    rootDir: OrgTechRepair
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Issuer
        value: OrgTechRepair
      - key: Jwt__Audience
        value: OrgTechRepair
      - key: Jwt__Key
        generateValue: true
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: orgtechrepair-db
          property: connectionString

databases:
  - name: orgtechrepair-db
    plan: free
